/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-3-7 下午3:00' with Gradle 2.1
 *
 * @author Administrator, @date 16-3-7 下午3:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
